package by.kotik.controller.command;

public enum CommandName {
    LOGINATION, REGISTRATION, GOTOMAINPAGE, SAVENEWUSER, LOGIN, GOTOWELCOMEPAGE, LOGOUT, GOTOADMINPAGE, ADMINISTRATION,
    SAVENEWCOFFEE, DELETECOFFEE, EDITCOFFEE, GOTOEDITCOFFEEPAGE, SAVENEWINGREDIENT, DELETEINGREDIENT, EDITINGREDIENT,
    GOTOEDITINGREDIENT
}
